# Basic Example Scripts
#
# ⚠️  IMPORTANT: These are EXAMPLE scripts for learning and getting started.
# These scripts are NOT meant for production use - they are educational tools!
#

scripts:
- name: hello
  description: Simple echo
  command: echo "Hello from script monitor!"
  log_limit:
    type: count
    value: 3
- name: show_date
  description: Show current date and time
  command: date
  log_limit:
    type: count
    value: 5
- name: current_dir
  description: Print current working directory
  command: pwd
  log_limit:
    type: count
    value: 5
- name: list_files
  description: List files in current directory
  command: ls -la
  log_limit:
    type: count
    value: 5
