# Basic Example Scripts
#
# ⚠️  IMPORTANT: These are EXAMPLE scripts for learning and getting started.
# These demonstrate basic signalbox functionality and are safe to run anywhere!
#
# This file contains simple scripts for getting started with signalbox:
# - Uses common shell commands that work on most systems
# - Perfect for initial testing and learning
# - These scripts are used in demo groups and error handling examples
# - All commands are safe and non-destructive (echo, date, pwd, ls)

scripts:
- name: hello
  description: Simple echo
  command: echo "Hello from script monitor!"
  log_limit:
    type: count
    value: 3
- name: show_date
  description: Show current date and time
  command: date
  log_limit:
    type: count
    value: 5
- name: current_dir
  description: Print current working directory
  command: pwd
  log_limit:
    type: count
    value: 5
- name: list_files
  description: List files in current directory
  command: ls -la
  log_limit:
    type: count
    value: 5
