# Test Scripts for Demonstration
#
# ⚠️  IMPORTANT: These are EXAMPLE scripts for learning and getting started.
# These scripts are NOT meant for production use - they are educational tools!
#
# PURPOSE: This file demonstrates error handling and testing scenarios:
# - Shows how signalbox handles script failures
# - Used in error handling demo groups to show stop_on_error behavior
# - Helps users understand the difference between success and failure states

scripts:
- name: fail_test
  description: Test failure (INTENTIONALLY FAILS for demo purposes)
  command: exit 1  # ← This command ALWAYS fails with exit code 1 - this is intentional!
  # NOTE: This script is used in error handling demos to show how signalbox behaves
  # when scripts fail. It's referenced in groups like 'error_handling_demo_stop' and
  # 'error_handling_demo_continue' to demonstrate stop_on_error behavior.
  log_limit:
    type: count
    value: 3
