# ============================================================================
# Global Configuration for signalbox
# ============================================================================

# Default log rotation settings (applied to scripts without specific log_limit)
default_log_limit:
  type: count
  value: 10

# Global paths
# - All .yaml/.yml files in script/group directory are loaded (appended together)
paths:
  log_dir: logs
  scripts_file: config/scripts  # Directory containing script YAML files
  groups_file: config/groups    # Directory containing group YAML files

# Execution settings
execution:
  # Default timeout for scripts (in seconds, 0 = no timeout)
  default_timeout: 300
  
  # Capture output settings
  capture_stdout: true
  capture_stderr: true
  
  # Maximum number of parallel workers for parallel group execution
  max_parallel_workers: 5

# Logging settings
logging:
  # Timestamp format for log files
  timestamp_format: "%Y%m%d_%H%M%S_%f"

# Display settings  
display:
  ## Date format for display 
  #   ∙ Alternative formats:
  #   ∙   "%y-%m-%d"                  →  25-10-20
  #   ∙   "%Y-%m-%d"                  →  2025-10-20
  #   ∙   "%m/%d/%y"                  →  10/20/25
  #   ∙   "%b %d, %Y"                 →  Oct 20, 2025
  #   ∙   "%Y-%m-%d %H:%M"            →  2025-10-20 13:59
  #   ∙   "%m/%d/%y %I:%M %p"         →  10/20/25 01:59 PM
  #   ∙   "%d %b %H:%M"               →  20 Oct 13:59
  date_format: "%d %b %H:%M"





# ============================================================================
# PLANNED FEATURES (NOT YET IMPLEMENTED)
# ============================================================================
# The options below are planned for future releases but are not currently
# functional. They are included here for documentation and future development.

# PLANNED: Export capabilities
planned_paths:
  systemd_export_dir: systemd  # Directory for exported systemd files
  cron_export_dir: cron        # Directory for exported cron files

# PLANNED: Advanced execution options
planned_execution:
  # Continue on error when running groups (deprecated - use group-level stop_on_error)
  continue_on_error: true

# PLANNED: Notification system
planned_notifications:
  enabled: false
  # on_failure: email
  # on_success: none
  # email: admin@example.com

# PLANNED: Scheduling system
planned_scheduling:
  # Default timezone for cron schedules
  timezone: UTC
  
  # Enable/disable all scheduled tasks
  enabled: true

# PLANNED: Enhanced logging
planned_logging:
  # Include command in log output
  include_command: true
  
  # Include return code in log output
  include_return_code: true

# PLANNED: Configuration validation
planned_validation:
  # Strict mode: fail on warnings
  strict: false
  
  # Check for unused scripts (defined but not in any group)
  warn_unused_scripts: true
  
  # Check for empty groups
  warn_empty_groups: true

# PLANNED: Display enhancements
planned_display:
  # Use colors in terminal output
  use_colors: true
  
  # Show full paths in output
  show_full_paths: false
