# Maintenance and Demo Groups Examples
#
# ⚠️  IMPORTANT: These are EXAMPLE groups for learning and getting started.
# These scripts are NOT meant for production use - they are educational tools!
#
# This file shows various execution patterns and error handling strategies:
#
# SCHEDULED MAINTENANCE (stop_on_error: false):
# - daily_maintenance & weekly_maintenance: Continue even if some tasks fail
#   because partial maintenance is better than no maintenance
#
# DEMONSTRATION GROUPS (for learning signalbox behavior):
# - error_handling_demo_stop: Shows how stop_on_error=true behaves
#   → fail_test script will STOP execution, remaining scripts won't run
# - error_handling_demo_continue: Shows how stop_on_error=false behaves  
#   → fail_test script will FAIL but remaining scripts still run
# - mixed_workload_demo: Shows parallel execution benefits with mixed timing
#   → Fast and slow scripts run simultaneously instead of sequentially
#
# EMERGENCY SCENARIOS:
# - emergency_response: Parallel execution for speed during incidents
# - development_environment_setup: Serial with stop-on-error for reliability
#
# NOTE: The 'fail_test' script is INTENTIONALLY designed to fail (exit 1)
# to demonstrate error handling - this is not a bug!

groups:
- name: daily_maintenance
  description: Daily system maintenance tasks (continues on errors)
  schedule: 0 2 * * *
  execution: serial
  stop_on_error: false
  scripts:
  - security_updates_check
  - check_disk_space
  - backup_system_config
  - cleanup_temp_files
  - check_running_services
- name: weekly_maintenance
  description: Weekly comprehensive maintenance
  schedule: 0 3 * * 0
  execution: serial
  stop_on_error: false
  scripts:
  - backup_system_config
  - security_updates_check
  - cleanup_temp_files
  - check_disk_space
  - check_memory_usage
  - check_system_load
  - run_tests
  - generate_documentation
- name: error_handling_demo_stop
  description: Demonstrate serial execution with stop-on-error
  execution: serial
  stop_on_error: true  # ← STOPS execution when fail_test fails
  scripts:
  - check_website_health  # ✓ This will succeed
  - fail_test             # ✗ This will FAIL (intentionally) and STOP here
  - check_memory_usage    # ⏸ This will NOT run (execution stopped)
  - check_disk_space      # ⏸ This will NOT run (execution stopped)
  # DEMO PURPOSE: Run this to see stop_on_error=true behavior

- name: error_handling_demo_continue
  description: Demonstrate serial execution continuing on errors
  execution: serial
  stop_on_error: false  # ← CONTINUES execution even when fail_test fails
  scripts:
  - check_website_health  # ✓ This will succeed
  - fail_test             # ✗ This will FAIL (intentionally) but execution continues
  - check_memory_usage    # ✓ This will still run despite previous failure
  - check_disk_space      # ✓ This will also run
  # DEMO PURPOSE: Run this to see stop_on_error=false behavior
- name: mixed_workload_demo
  description: Mix of fast and slow operations (shows parallel benefits)
  execution: parallel
  scripts:
  - show_date
  - check_website_health
  - run_performance_tests
  - check_dns_resolution
  - security_scan
- name: emergency_response
  description: Emergency system check and recovery
  execution: parallel
  scripts:
  - check_system_load
  - check_memory_usage
  - check_disk_space
  - check_running_services
  - check_network_connectivity
  - check_website_health
- name: development_environment_setup
  description: Set up and verify development environment
  execution: serial
  stop_on_error: true
  scripts:
  - check_running_services
  - run_tests
  - lint_code
  - security_scan
  - build_project
